version: '3'
services:
  redkina:
    build:
      context: .
    depends_on:
      - redis
    entrypoint: tail -f /dev/null
    working_dir: /usr/src/redkina
    environment:
      XDEBUG_CONFIG: remote_host=host.docker.internal
      PHP_IDE_CONFIG: serverName=redkina.localhost
      COMPOSER_ALLOW_SUPERUSER: 1
    volumes:
      - .:/usr/src/redkina
      - ./docker/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    networks:
      - redkina
  redis:
    image: redis:alpine
    ports:
      - "6384:6379"
    networks:
      - redkina
networks:
  redkina:
    external: false
